using Microsoft.Data.Sqlite;

namespace Archive.Infrastructure.Scheduling;

public static class QuartzSchemaInitializer
{
    private static readonly string[] Statements =
    [
        """
        CREATE TABLE IF NOT EXISTS QRTZ_JOB_DETAILS (
            SCHED_NAME TEXT NOT NULL,
            JOB_NAME TEXT NOT NULL,
            JOB_GROUP TEXT NOT NULL,
            DESCRIPTION TEXT NULL,
            JOB_CLASS_NAME TEXT NOT NULL,
            IS_DURABLE INTEGER NOT NULL,
            IS_NONCONCURRENT INTEGER NOT NULL,
            IS_UPDATE_DATA INTEGER NOT NULL,
            REQUESTS_RECOVERY INTEGER NOT NULL,
            JOB_DATA BLOB NULL,
            PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_TRIGGERS (
            SCHED_NAME TEXT NOT NULL,
            TRIGGER_NAME TEXT NOT NULL,
            TRIGGER_GROUP TEXT NOT NULL,
            JOB_NAME TEXT NOT NULL,
            JOB_GROUP TEXT NOT NULL,
            DESCRIPTION TEXT NULL,
            NEXT_FIRE_TIME INTEGER NULL,
            PREV_FIRE_TIME INTEGER NULL,
            PRIORITY INTEGER NULL,
            TRIGGER_STATE TEXT NOT NULL,
            TRIGGER_TYPE TEXT NOT NULL,
            START_TIME INTEGER NOT NULL,
            END_TIME INTEGER NULL,
            CALENDAR_NAME TEXT NULL,
            MISFIRE_INSTR INTEGER NULL,
            JOB_DATA BLOB NULL,
            PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
            FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
                REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_SIMPLE_TRIGGERS (
            SCHED_NAME TEXT NOT NULL,
            TRIGGER_NAME TEXT NOT NULL,
            TRIGGER_GROUP TEXT NOT NULL,
            REPEAT_COUNT INTEGER NOT NULL,
            REPEAT_INTERVAL INTEGER NOT NULL,
            TIMES_TRIGGERED INTEGER NOT NULL,
            PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
            FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS (
            SCHED_NAME TEXT NOT NULL,
            TRIGGER_NAME TEXT NOT NULL,
            TRIGGER_GROUP TEXT NOT NULL,
            CRON_EXPRESSION TEXT NOT NULL,
            TIME_ZONE_ID TEXT NULL,
            PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
            FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_SIMPROP_TRIGGERS (
            SCHED_NAME TEXT NOT NULL,
            TRIGGER_NAME TEXT NOT NULL,
            TRIGGER_GROUP TEXT NOT NULL,
            STR_PROP_1 TEXT NULL,
            STR_PROP_2 TEXT NULL,
            STR_PROP_3 TEXT NULL,
            INT_PROP_1 INTEGER NULL,
            INT_PROP_2 INTEGER NULL,
            LONG_PROP_1 INTEGER NULL,
            LONG_PROP_2 INTEGER NULL,
            DEC_PROP_1 NUMERIC NULL,
            DEC_PROP_2 NUMERIC NULL,
            BOOL_PROP_1 INTEGER NULL,
            BOOL_PROP_2 INTEGER NULL,
            PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
            FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_BLOB_TRIGGERS (
            SCHED_NAME TEXT NOT NULL,
            TRIGGER_NAME TEXT NOT NULL,
            TRIGGER_GROUP TEXT NOT NULL,
            BLOB_DATA BLOB NULL,
            PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
            FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
                ON DELETE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS (
            SCHED_NAME TEXT NOT NULL,
            CALENDAR_NAME TEXT NOT NULL,
            CALENDAR BLOB NOT NULL,
            PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_PAUSED_TRIGGER_GRPS (
            SCHED_NAME TEXT NOT NULL,
            TRIGGER_GROUP TEXT NOT NULL,
            PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_FIRED_TRIGGERS (
            SCHED_NAME TEXT NOT NULL,
            ENTRY_ID TEXT NOT NULL,
            TRIGGER_NAME TEXT NOT NULL,
            TRIGGER_GROUP TEXT NOT NULL,
            INSTANCE_NAME TEXT NOT NULL,
            FIRED_TIME INTEGER NOT NULL,
            SCHED_TIME INTEGER NOT NULL,
            PRIORITY INTEGER NOT NULL,
            STATE TEXT NOT NULL,
            JOB_NAME TEXT NULL,
            JOB_GROUP TEXT NULL,
            IS_NONCONCURRENT INTEGER NULL,
            REQUESTS_RECOVERY INTEGER NULL,
            PRIMARY KEY (SCHED_NAME, ENTRY_ID)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_SCHEDULER_STATE (
            SCHED_NAME TEXT NOT NULL,
            INSTANCE_NAME TEXT NOT NULL,
            LAST_CHECKIN_TIME INTEGER NOT NULL,
            CHECKIN_INTERVAL INTEGER NOT NULL,
            PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS QRTZ_LOCKS (
            SCHED_NAME TEXT NOT NULL,
            LOCK_NAME TEXT NOT NULL,
            PRIMARY KEY (SCHED_NAME, LOCK_NAME)
        );
        """,
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS(SCHED_NAME, REQUESTS_RECOVERY);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS(SCHED_NAME, JOB_GROUP);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_J ON QRTZ_TRIGGERS(SCHED_NAME, JOB_NAME, JOB_GROUP);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_JG ON QRTZ_TRIGGERS(SCHED_NAME, JOB_GROUP);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_C ON QRTZ_TRIGGERS(SCHED_NAME, CALENDAR_NAME);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_G ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_GROUP);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_STATE);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(SCHED_NAME, NEXT_FIRE_TIME);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_NFT_ST_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON QRTZ_TRIGGERS(SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, INSTANCE_NAME);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, JOB_NAME, JOB_GROUP);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, JOB_GROUP);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);",
        "CREATE INDEX IF NOT EXISTS IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME, TRIGGER_GROUP);"
    ];

    public static void EnsureCreated(string connectionString)
    {
        using var connection = new SqliteConnection(connectionString);
        connection.Open();

        foreach (var statement in Statements)
        {
            using var command = connection.CreateCommand();
            command.CommandText = statement;
            command.ExecuteNonQuery();
        }
    }
}