// <auto-generated />
using System;
using Archive.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Archive.Infrastructure.Migrations
{
    [DbContext(typeof(ArchiveDbContext))]
    partial class ArchiveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Archive.Core.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ComparisonMethod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedFileHandling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("NotifyOnComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NotifyOnFail")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NotifyOnStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverwriteBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SimpleTriggerTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SyncOptionsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncOptionsId");

                    b.ToTable("BackupJobs");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.BackupJobExclusionPattern", b =>
                {
                    b.Property<Guid>("BackupJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExclusionPatternId")
                        .HasColumnType("TEXT");

                    b.HasKey("BackupJobId", "ExclusionPatternId");

                    b.HasIndex("ExclusionPatternId");

                    b.ToTable("BackupJobExclusionPatterns");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.ExclusionPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemSuggestion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExclusionPatterns");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.ExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobExecutionId");

                    b.ToTable("ExecutionLogs");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.JobExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesCopied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesScanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobExecutions");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.SyncOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteOrphaned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recursive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipHiddenAndSystem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifyAfterCopy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncOptions");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.BackupJob", b =>
                {
                    b.HasOne("Archive.Core.Domain.Entities.SyncOptions", "SyncOptions")
                        .WithMany("BackupJobs")
                        .HasForeignKey("SyncOptionsId");

                    b.Navigation("SyncOptions");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.BackupJobExclusionPattern", b =>
                {
                    b.HasOne("Archive.Core.Domain.Entities.BackupJob", "BackupJob")
                        .WithMany("BackupJobExclusionPatterns")
                        .HasForeignKey("BackupJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive.Core.Domain.Entities.ExclusionPattern", "ExclusionPattern")
                        .WithMany("BackupJobExclusionPatterns")
                        .HasForeignKey("ExclusionPatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupJob");

                    b.Navigation("ExclusionPattern");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.ExecutionLog", b =>
                {
                    b.HasOne("Archive.Core.Domain.Entities.JobExecution", "Execution")
                        .WithMany("Logs")
                        .HasForeignKey("JobExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.JobExecution", b =>
                {
                    b.HasOne("Archive.Core.Domain.Entities.BackupJob", "Job")
                        .WithMany("Executions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.BackupJob", b =>
                {
                    b.Navigation("BackupJobExclusionPatterns");

                    b.Navigation("Executions");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.ExclusionPattern", b =>
                {
                    b.Navigation("BackupJobExclusionPatterns");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.JobExecution", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Archive.Core.Domain.Entities.SyncOptions", b =>
                {
                    b.Navigation("BackupJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
